
backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.en.md"
        label: "Home (EN)"
        name: "home_en"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/index.fr.md"
        label: "Accueil (FR)"
        name: "home_fr"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Video URL", name: "video", widget: "string", required: false}
      - {label: "Quote", name: "quote", widget: "text"}
